# ====================================================================================
# Inputs and configuration

inputs:
<% for (const [plugin, {name, action}] of Object.entries(plugins)) { %>
  # ====================================================================================
  # <%- name %>
  <% for (const [input, {descriptor}] of Object.entries(action)) { %>
  <%- descriptor.split("\n").map((line, i) => `${i ? "  " : ""}${line}`).join("\n") -%>
<% }} %>

# ====================================================================================
# Action metadata
name: Metrics embed
author: lowlighter
description: An infographics generator with 40+ plugins and 300+ options to display stats about your GitHub account!
branding:
  icon: user-check
  color: gray-dark

# The action will parse its name to check if it's the official action or if it's a forked one
# On the official action, it'll use the docker image published on GitHub registry when using a released version, allowing faster runs
# On a forked action, it'll rebuild the docker image from Dockerfile to take into account changes you made
runs:
  using: composite
  steps:
    - run: |
        <%- runsh.split("\n").map((line, i) => `${i ? "        " : ""}${line}`).join("\n") %>
      shell: bash
      env:
        METRICS_ACTION: ${{ github.action }}
        METRICS_ACTION_PATH: ${{ github.action_path }}
        METRICS_USE_PREBUILT_IMAGE: ${{ inputs.use_prebuilt_image }}
        INPUTS: ${{ toJson(inputs) }}
        TZ: ${{ inputs.config_timezone }}
