📊 metrics embed:
  - source/app/action/**
  - source/app/web/**
✨ metrics insights:
  - source/app/web/statics/insights/**

🧩 plugins:
  - source/plugins/**
🖼️ templates:
  - source/templates/**

🗃️ base:
  - source/plugins/base/**
🧱 core:
  - source/app/metrics/**
  - source/plugins/core/**

🎲 community plugins:
  - source/plugins/community/**

🏆 plugin achievements:
  - source/plugins/achievements/**
📰 plugin activity:
  - source/plugins/activity/**
🌸 plugin anilist:
  - source/plugins/anilist/**
📆 plugin calendar:
  - source/plugins/calendar/**
♐ plugin code:
  - source/plugins/code/**
🏅 plugin contributors:
  - source/plugins/contributors/**
💬 plugin discussions:
  - source/plugins/discussions/**
🎟️ plugin followup:
  - source/plugins/followup/**
🎫 plugin gists:
  - source/plugins/gists/**
💡 plugin habits:
  - source/plugins/habits/**
🙋 plugin introduction:
  - source/plugins/introduction/**
📅 plugin isocalendar:
  - source/plugins/isocalendar/**
🈷️ plugin languages:
  - source/plugins/languages/**
🗳️ plugin leetcode:
  - source/plugins/leetcode/**
📜 plugin licenses:
  - source/plugins/licenses/**
👨‍💻 plugin lines:
  - source/plugins/lines/**
🎼 plugin music:
  - source/plugins/music/**
🎩 plugin notable:
  - source/plugins/notable/**
⏱️ plugin pagespeed:
  - source/plugins/pagespeed/**
🧑‍🤝‍🧑 plugin people:
  - source/plugins/people/**
✒️ plugin posts:
  - source/plugins/posts/**
🗂️ plugin projects:
  - source/plugins/projects/**
🎭 plugin reactions:
  - source/plugins/reactions/**
📓 plugin repositories:
  - source/plugins/repositories/**
🗼 plugin rss:
  - source/plugins/rss/**
🌇 plugin skyline:
  - source/plugins/skyline/**
💕 plugin sponsors:
  - source/plugins/sponsors/**
🗨️ plugin stackoverflow:
  - source/plugins/stackoverflow/**
✨ plugin stargazers:
  - source/plugins/stargazers/**
💫 plugin starlists:
  - source/plugins/starlists/**
🌟 plugin stars:
  - source/plugins/stars/**
💭 plugin support:
  - source/plugins/support/**
📌 plugin topics:
  - source/plugins/topics/**
🧮 plugin traffic:
  - source/plugins/traffic/**
🐤 plugin tweets:
  - source/plugins/tweets/**
⏰ plugin wakatime:
  - source/plugins/wakatime/**