name: 🖼️ Template name
extends: classic
description: |
  Short description
examples:
  default: https://via.placeholder.com/468x60?text=No%20preview%20available
authors:
  - octocat
supports:
  - user
  - organization
  - repository
formats:
  - svg
  - png
  - jpeg
  - json
  - markdown
  - markdown-pdf
